export enum UserRole {
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  USER = 'USER',
}

export enum MembershipRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  PROVIDER = 'PROVIDER',
}

export enum AppointmentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum ConsultationType {
  VIDEO = 'VIDEO',
  IN_PERSON = 'IN_PERSON',
  PHONE = 'PHONE',
  BOTH = 'BOTH',
}

export enum VideoRoomStatus {
  CREATED = 'CREATED',
  WAITING = 'WAITING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
}

export enum ConfirmationMode {
  AUTO_CONFIRM = 'AUTO_CONFIRM',
  MANUAL_APPROVAL = 'MANUAL_APPROVAL',
}

export enum CalendarProvider {
  GOOGLE = 'GOOGLE',
  OUTLOOK = 'OUTLOOK',
}

export enum CalendarEventDirection {
  OUTBOUND = 'OUTBOUND',
  INBOUND = 'INBOUND',
}

export enum CalendarConnectionStatus {
  ACTIVE = 'ACTIVE',
  DISCONNECTED = 'DISCONNECTED',
  ERROR = 'ERROR',
}

export enum MessageType {
  TEXT = 'TEXT',
  SYSTEM = 'SYSTEM',
}

export enum IntakeFieldType {
  TEXT = 'TEXT',
  TEXTAREA = 'TEXTAREA',
  SELECT = 'SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
  CHECKBOX = 'CHECKBOX',
  DATE = 'DATE',
  NUMBER = 'NUMBER',
  PHONE = 'PHONE',
  EMAIL = 'EMAIL',
}

export enum IntakeStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  NOT_REQUIRED = 'NOT_REQUIRED',
}

export enum NotificationType {
  APPOINTMENT_CONFIRMED = 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_RESCHEDULED = 'APPOINTMENT_RESCHEDULED',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  NEW_MESSAGE = 'NEW_MESSAGE',
  INTAKE_FORM_COMPLETED = 'INTAKE_FORM_COMPLETED',
  VIDEO_ROOM_READY = 'VIDEO_ROOM_READY',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  PATIENT_IN_WAITING_ROOM = 'PATIENT_IN_WAITING_ROOM',
}

export enum SpecialtyCategory {
  PRIMARY_CARE = 'PRIMARY_CARE',
  MENTAL_HEALTH = 'MENTAL_HEALTH',
  DENTAL = 'DENTAL',
  DERMATOLOGY = 'DERMATOLOGY',
  PHYSICAL_THERAPY = 'PHYSICAL_THERAPY',
  SPECIALIST = 'SPECIALIST',
  OTHER = 'OTHER',
}

export enum ConsentType {
  TERMS_OF_SERVICE = 'TERMS_OF_SERVICE',
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  DATA_PROCESSING = 'DATA_PROCESSING',
  SMS_OPT_IN = 'SMS_OPT_IN',
  VIDEO_RECORDING = 'VIDEO_RECORDING',
}

export enum AuditAction {
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PRACTICE_CREATED = 'PRACTICE_CREATED',
  PRACTICE_UPDATED = 'PRACTICE_UPDATED',
  PROVIDER_ADDED = 'PROVIDER_ADDED',
  PROVIDER_REMOVED = 'PROVIDER_REMOVED',
  APPOINTMENT_CREATED = 'APPOINTMENT_CREATED',
  APPOINTMENT_CONFIRMED = 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_RESCHEDULED = 'APPOINTMENT_RESCHEDULED',
  VIDEO_ROOM_CREATED = 'VIDEO_ROOM_CREATED',
  VIDEO_ROOM_JOINED = 'VIDEO_ROOM_JOINED',
  VIDEO_ROOM_ENDED = 'VIDEO_ROOM_ENDED',
  INTAKE_VIEWED = 'INTAKE_VIEWED',
  INTAKE_SUBMITTED = 'INTAKE_SUBMITTED',
  PAYMENT_CREATED = 'PAYMENT_CREATED',
  PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  MESSAGE_SENT = 'MESSAGE_SENT',
  STRIPE_CONNECTED = 'STRIPE_CONNECTED',
  CALENDAR_CONNECTED = 'CALENDAR_CONNECTED',
  CALENDAR_DISCONNECTED = 'CALENDAR_DISCONNECTED',
  PATIENT_DATA_EXPORT = 'PATIENT_DATA_EXPORT',
}

export enum UploadPurpose {
  AVATAR = 'avatar',
  PRACTICE_LOGO = 'practice_logo',
  PRACTICE_COVER = 'practice_cover',
}

export enum DayOfWeek {
  SUNDAY = 0,
  MONDAY = 1,
  TUESDAY = 2,
  WEDNESDAY = 3,
  THURSDAY = 4,
  FRIDAY = 5,
  SATURDAY = 6,
}

export enum InvitationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REVOKED = 'REVOKED',
  EXPIRED = 'EXPIRED',
}
